Repository Pmacdon15/final_project_web, pull requests merged in 2024-11, with the labels that each got.

#91 Completed DB Schema, did a few basic set ups for 3 routes.
  .vscode/settings.json
  backend/index.js
  backend/package.json
  backend/public/programs.html
  backend/src/app.js
  backend/src/contollers/course.controller.js
  backend/src/contollers/user.controller.js
  backend/src/controllers/courses.controller.js
  backend/src/controllers/programs.controller.js
  backend/src/controllers/sample.controller.js
  backend/src/controllers/user.controller.js
  backend/src/models/schema.model.sql
  backend/src/routes/course.routes.js
  backend/src/routes/courses.routes.js
  backend/src/routes/programs.routes.js
  backend/src/routes/sample.routes.js
  backend/src/routes/user.routes.js
Labels: enhancement

#94 add removeUserCourse endpoint
  backend/src/controllers/courses.controller.js
  backend/src/models/schema.model.sql
  backend/src/routes/courses.routes.js
Labels: enhancement

#95 Add User Course
  backend/src/controllers/courses.controller.js
  backend/src/models/schema.model.sql
  backend/src/routes/courses.routes.js
Labels: enhancement

#97 Added API route from remove courses as an admin
  backend/src/controllers/courses.controller.js
  backend/src/models/schema.model.sql
  backend/src/routes/courses.routes.js
Labels: enhancement

#98 Added route to remove program from programs as admin
  backend/src/controllers/programs.controller.js
  backend/src/routes/programs.routes.js
Labels: enhancement

#99 Create LICENSE
  LICENSE
Labels: documentation

#100 Added route for admin to add a program
  backend/src/controllers/programs.controller.js
  backend/src/models/schema.model.sql
  backend/src/routes/programs.routes.js
Labels: enhancement

#101 Added edit a program admin route
  backend/src/controllers/programs.controller.js
  backend/src/models/schema.model.sql
  backend/src/routes/programs.routes.js
Labels: enhancement

#102 Add models
  backend/src/app.js
  backend/src/controllers/courses.controller.js
  backend/src/controllers/programs.controller.js
  backend/src/controllers/users.controller.js
  backend/src/models/course.model.js
  backend/src/models/courses.model.js
  backend/src/models/programs.model.js
  backend/src/models/schema.model.sql
  backend/src/models/user.model.js
  backend/src/models/users.model.js
  backend/src/routes/courses.routes.js
  backend/src/routes/programs.routes.js
  backend/src/routes/user.routes.js
Labels: enhancement

#108 Refactor signup routes to users
  .vscode/settings.json
  backend/package-lock.json
  backend/package.json
  backend/src/app.js
  backend/src/controllers/adminCourses.controller.js
  backend/src/controllers/auth.controller.js
  backend/src/controllers/programs.controller.js
  backend/src/controllers/sample.controller.js
  backend/src/controllers/signUp.controller.js
  backend/src/controllers/users.controller.js
  backend/src/middlewares/auth.middleware.js
  backend/src/models/adminPrograms.model.js
  backend/src/models/sample.model.sql
  backend/src/models/schema.model.sql
  backend/src/models/signUp.model.js
  backend/src/models/users.model.js
  backend/src/routes/AdminUsers.routes.js
  backend/src/routes/adminCourses.routes.js
  backend/src/routes/adminPrograms.routes.js
  backend/src/routes/clientCourses.routes.js
  backend/src/routes/clientUsers.routes.js
  backend/src/routes/courses.routes.js
  backend/src/routes/programs.routes.js
  backend/src/routes/sample.routes.js
  backend/src/routes/user.routes.js
Labels: enhancement

#112 Api to comments
  backend/src/app.js
  backend/src/controllers/admin.comment.controller.js
  backend/src/controllers/clientComment.controller.js
  backend/src/middlewares/comment.middleware.js
  backend/src/middlewares/isAdmin.middleware.js
  backend/src/models/admin.comment.model.js
  backend/src/models/clientComment.model.js
  backend/src/routes/AdminUsers.routes.js
  backend/src/routes/ClientComment.routes.js
  backend/src/routes/adminComment.routes.js
Labels: enhancement

#115 Added the remaining routes, improved code quality, and consistency
  backend/package-lock.json
  backend/package.json
  backend/src/app.js
  backend/src/controllers/admin.comment.controller.js
  backend/src/controllers/adminCourses.controller.js
  backend/src/controllers/auth.controller.js
  backend/src/controllers/clientComment.controller.js
  backend/src/controllers/courses.controller.js
  backend/src/controllers/programs.controller.js
  backend/src/controllers/users.controller.js
  backend/src/middlewares/multer.middleware.js
  backend/src/models/clientComment.model.js
  backend/src/models/users.model.js
  backend/src/routes/ClientComment.routes.js
  backend/src/routes/auth.routes.js
  backend/src/utils/apiError.js
  backend/src/utils/apiResponse.js
  backend/src/utils/asyncHandler.js
  backend/src/utils/cloudinary.js
Labels: enhancement

#117 add feature to block users from enrolling to more than 5 courses by term
  .gitignore
  backend/package.json
  backend/src/app.js
  backend/src/controllers/courses.controller.js
  backend/src/models/courses.model.js
  backend/src/routes/auth.routes.js
  backend/src/routes/clientCourses.routes.js
Labels: bug, enhancement
